DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS message;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE message (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL,
  FOREIGN KEY (author) REFERENCES user (id)
);

CREATE TABLE chat (
  first_user INTEGER REFERENCES user,
  second_user INTEGER REFERENCES user,
  PRIMARY KEY (first_user, second_user)
);
